version: '3'

volumes:
  pg_data2:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data2:/var/lib/postgresql/data
  backend:
    image: antony41991/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
  frontend:
    env_file: .env
    image: antony41991/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: antony41991/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
